jenkins:
  clouds:
  - kubernetes:
      name: "kubernetes"
      serverUrl: "https://kubernetes.default"
      jenkinsUrl: "http://jenkins:8080"
      jenkinsTunnel: "jenkins-agent:50000"
      containerCapStr: "2"
      maxRequestsPerHostStr: "32"
unclassified:
  globalLibraries:
    libraries:
      - name: "jenkins-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/RicoToothless/coscup-jenkins-demo-library.git"
jobs:
  - script: |
      pipelineJob("demo01") {
          definition {
              cpsScm{
                  scm{
                      git {
                          remote{
                              name('origin')
                              url('https://github.com/RicoToothless/coscup-jenkins-demo-library.git')
                          }
                      }
                  }
                  scriptPath("testjobs/demo01_Jenkinsfile.groovy")
              }
          }
      }
      pipelineJob("demo02") {
          definition {
              cpsScm{
                  scm{
                      git {
                          remote{
                              name('origin')
                              url('https://github.com/RicoToothless/coscup-jenkins-demo-library.git')
                          }
                      }
                  }
                  scriptPath("testjobs/demo02_Jenkinsfile.groovy")
              }
          }
      }